In [1]:
import galah

### Australian atlas

In [3]:
galah.galah_config(atlas="Australia")
galah.atlas_species(taxa="Vulpes")#,rank="subspecies"

,kingdom,phylum,class,order,family,genus,species,subspecies,vernacular_name,author,guid
0,Animalia,Chordata,Mammalia,Carnivora,Canidae,Vulpes,Vulpes vulpes,Vulpes vulpes vulpes,,"Linnaeus, 1758",Https://biodiversity.org.au/afd/taxa/f9971f49-...

In [5]:
galah.atlas_species(taxa="Limnodynastidae")

,kingdom,phylum,class,order,family,genus,species,vernacular_name,author,guid
0,Animalia,Chordata,Amphibia,Anura,Limnodynastidae,Limnodynastes,Limnodynastes peronii,"Brown-Striped Frog, Striped Marsh Frog","(duméril & bibron, 1841)",Https://biodiversity.org.au/afd/taxa/475b04bd-...
1,Animalia,Chordata,Amphibia,Anura,Limnodynastidae,Limnodynastes,Limnodynastes tasmaniensis,"Spotted Grass Frog, Spotted Marsh Frog","Günther, 1858",Https://biodiversity.org.au/afd/taxa/ac2de3ed-...
2,Animalia,Chordata,Amphibia,Anura,Limnodynastidae,Limnodynastes,Limnodynastes dumerilii,Eastern Banjo Frog,"Peters, 1863",Https://biodiversity.org.au/afd/taxa/2c50c2f6-...
3,Animalia,Chordata,Amphibia,Anura,Limnodynastidae,Platyplectrum,Platyplectrum ornatum,"Ornate Burrowing Frog, Balgawalgirrnya, Maguju...","(gray, 1842)",Https://biodiversity.org.au/afd/taxa/2e224aea-...
4,Animalia,Chordata,Amphibia,Anura,Limnodynastidae,Adelotus,Adelotus brevis,Tusked Frog,"(günther, 1863)",Https://biodiversity.org.au/afd/taxa/32f57cc7-...
5,Animalia,Chordata,Amphibia,Anura,Limnodynastidae,Neobatrachus,Neobatrachus sudellae,"Sudell's Frog, Galgalbanaa","(lamb, 1911)",Https://biodiversity.org.au/afd/taxa/953a5af4-...
6,Animalia,Chordata,Amphibia,Anura,Limnodynastidae,Limnodynastes,Limnodynastes fletcheri,"Barking Frog, Long-Thumbed Frog, Marsh Frog","Boulenger, 1888",Https://biodiversity.org.au/afd/taxa/89785c3b-...
7,Animalia,Chordata,Amphibia,Anura,Limnodynastidae,Limnodynastes,Limnodynastes convexiusculus,"Marbled Frog, A-Garhmang, Bakuŋbakuŋ, Frogfrog...","(macleay, 1877)",Https://biodiversity.org.au/afd/taxa/066d749e-...
8,Animalia,Chordata,Amphibia,Anura,Limnodynastidae,Limnodynastes,Limnodynastes terraereginae,Northern Banjo Frog,"Fry, 1915",Https://biodiversity.org.au/afd/taxa/7bdd975a-...
9,Animalia,Chordata,Amphibia,Anura,Limnodynastidae,Limnodynastes,Limnodynastes dorsalis,"Bullfrog, Western Banjo Frog","(gray, 1841)",Https://biodiversity.org.au/afd/taxa/ac5ce2ed-...
10,Animalia,Chordata,Amphibia,Anura,Limnodynastidae,Heleioporus,Heleioporus eyrei,Moaning Frog,"(gray, 1845)",Https://biodiversity.org.au/afd/taxa/cf991494-...
11,Animalia,Chordata,Amphibia,Anura,Limnodynastidae,Neobatrachus,Neobatrachus pictus,"Painted Burrowing Frog, Painted Frog","Peters, 1863",Https://biodiversity.org.au/afd/taxa/39eeb892-...
12,Animalia,Chordata,Amphibia,Anura,Limnodynastidae,Notaden,Notaden nichollsi,Desert Spadefoot,"Parker, 1940",Https://biodiversity.org.au/afd/taxa/5862d01c-...
13,Animalia,Chordata,Amphibia,Anura,Limnodynastidae,Limnodynastes,Limnodynastes interioris,"Giant Banjo Frog, Giant Bullfrog","Fry, 1913",Https://biodiversity.org.au/afd/taxa/880ef4e5-...
14,Animalia,Chordata,Amphibia,Anura,Limnodynastidae,Limnodynastes,Limnodynastes salmini,"Salmon Striped Frog, Baaybal","Steindachner, 1867",Https://biodiversity.org.au/afd/taxa/60bcfa1d-...
15,Animalia,Chordata,Amphibia,Anura,Limnodynastidae,Lechriodus,Lechriodus fletcheri,Fletcher's Frog,"(boulenger, 1890)",Https://biodiversity.org.au/afd/taxa/fd657a65-...
16,Animalia,Chordata,Amphibia,Anura,Limnodynastidae,Heleioporus,Heleioporus australiacus,Giant Burrowing Frog,"(shaw & nodder, 1795)",Https://biodiversity.org.au/afd/taxa/20119b25-...
17,Animalia,Chordata,Amphibia,Anura,Limnodynastidae,Platyplectrum,Platyplectrum spenceri,"Spencer's Burrowing Frog, Spencer's Frog","(parker, 1940)",Https://biodiversity.org.au/afd/taxa/2e1eaf74-...
18,Animalia,Chordata,Amphibia,Anura,Limnodynastidae,Notaden,Notaden melanoscaphus,"Northern Spadefoot, A-Garhmang, Bakuŋbakuŋ, Fr...","Hosmer, 1962",Https://biodiversity.org.au/afd/taxa/0d32d548-...
19,Animalia,Chordata,Amphibia,Anura,Limnodynastidae,Philoria,Philoria sphagnicola,Sphagnum Frog,"(moore, 1958)",Https://biodiversity.org.au/afd/taxa/986352a5-...
20,Animalia,Chordata,Amphibia,Anura,Limnodynastidae,Notaden,Notaden bennettii,"Crucifix Frog, Holy Cross Frog, Bulga","Günther, 1873",Https://biodiversity.org.au/afd/taxa/24afae61-...
21,Animalia,Chordata,Amphibia,Anura,Limnodynastidae,Neobatrachus,Neobatrachus pelobatoides,Humming Frog,"(werner, 1914)",Https://biodiversity.org.au/afd/taxa/0a2d3c77-...
22,Animalia,Chordata,Amphibia,Anura,Limnodynastidae,Neobatrachus,Neobatrachus sutor,Shoemaker Frog,"Main, 1957",Https://biodiversity.org.au/afd/taxa/3788cffe-...
23,Animalia,Chordata,Amphibia,Anura,Limnodynastidae,Heleioporus,Heleioporus albopunctatus,Western Spotted Frog,"Gray, 1841",Https://biodiversity.org.au/afd/taxa/c1d18a1e-...
24,Animalia,Chordata,Amphibia,Anura,Limnodynastidae,Neobatrachus,Neobatrachus kunapalari,"Kunapalari Frog, Wheatbelt Frog","Mahony & roberts, 1986",Https://biodiversity.org.au/afd/taxa/6f344f2a-...
25,Animalia,Chordata,Amphibia,Anura,Limnodynastidae,Philoria,Philoria loveridgei,Loveridge's Frog,"Parker, 1940",Https://biodiversity.org.au/afd/taxa/f1e8b187-...
26,Animalia,Chordata,Amphibia,Anura,Limnodynastidae,Neobatrachus,Neobatrachus aquilonius,Northern Burrowing Frog,"Tyler, davies & martin, 1981",Https://biodiversity.org.au/afd/taxa/ff35671b-...
27,Animalia,Chordata,Amphibia,Anura,Limnodynastidae,Philoria,Philoria frosti,Baw Baw Frog,"Spencer, 1901",Https://biodiversity.org.au/afd/taxa/c0bc8e92-...
28,Animalia,Chordata,Amphibia,Anura,Limnodynastidae,Neobatrachus,Neobatrachus wilsmorei,Goldfields Bullfrog,"(parker, 1940)",Https://biodiversity.org.au/afd/taxa/1ddf3536-...
29,Animalia,Chordata,Amphibia,Anura,Limnodynastidae,Limnodynastes,Limnodynastes lignarius,"Carpenter Frog, Woodworker Frog, A-Garhmang, B...","(tyler, martin & davies, 1979)",Https://biodiversity.org.au/afd/taxa/201932e4-...
30,Animalia,Chordata,Amphibia,Anura,Limnodynastidae,Heleioporus,Heleioporus psammophilus,Sand Frog,"(lee & main, 1954)",Https://biodiversity.org.au/afd/taxa/0efbf288-...
31,Animalia,Chordata,Amphibia,Anura,Limnodynastidae,Philoria,Philoria kundagungan,"Mountain Frog, Red-And-Yellow Mountainfrog","(ingram & corben, 1975)",Https://biodiversity.org.au/afd/taxa/fcb2e700-...
32,Animalia,Chordata,Amphibia,Anura,Limnodynastidae,Neobatrachus,Neobatrachus albipes,White-Footed Frog,"Roberts, mahony, kendrick & majors, 1991",Https://biodiversity.org.au/afd/taxa/d9b8c071-...
33,Animalia,Chordata,Amphibia,Anura,Limnodynastidae,Philoria,Philoria pughi,"Pugh's Frog, Pugh's Sphagnum Frog","Knowles, mahony, armstrong & donnellan, 2004",Https://biodiversity.org.au/afd/taxa/1f800926-...
34,Animalia,Chordata,Amphibia,Anura,Limnodynastidae,Heleioporus,Heleioporus barycragus,"Hooting Frog, Western Marsh Frog","Lee, 1967",Https://biodiversity.org.au/afd/taxa/c527388c-...
35,Animalia,Chordata,Amphibia,Anura,Limnodynastidae,Heleioporus,Heleioporus inornatus,"Plains Frog, Whooping Frog","(lee & main, 1954)",Https://biodiversity.org.au/afd/taxa/16fcc761-...
36,Animalia,Chordata,Amphibia,Anura,Limnodynastidae,Limnodynastes,Limnodynastes depressus,Flat-Headed Frog,"Tyler, 1976",Https://biodiversity.org.au/afd/taxa/42c7d977-...
37,Animalia,Chordata,Amphibia,Anura,Limnodynastidae,Neobatrachus,Neobatrachus fulvus,Tawny Frog,"Mahony & roberts, 1986",Https://biodiversity.org.au/afd/taxa/c659f7db-...
38,Animalia,Chordata,Amphibia,Anura,Limnodynastidae,Philoria,Philoria richmondensis,"Richmond Frog, Richmond Range Sphagnum Frog","Knowles, mahony, armstrong & donnellan, 2004",Https://biodiversity.org.au/afd/taxa/df58b980-...
39,Animalia,Chordata,Amphibia,Anura,Limnodynastidae,Notaden,Notaden weigeli,"Weigel's Spadefoot Toad, Weigel's Toad","Shea & johnston, 1988",Https://biodiversity.org.au/afd/taxa/7ccf02f7-...

In [6]:
galah.atlas_species(taxa="Limnodynastidae",rank="genus")

,kingdom,phylum,class,order,family,genus,vernacular_name,author,guid
0,Animalia,Chordata,Amphibia,Anura,Limnodynastidae,Limnodynastes,,"Fitzinger, 1843",Https://biodiversity.org.au/afd/taxa/755a50a2-...
1,Animalia,Chordata,Amphibia,Anura,Limnodynastidae,Platyplectrum,,"Günther, 1863",Https://biodiversity.org.au/afd/taxa/f55b1af2-...
2,Animalia,Chordata,Amphibia,Anura,Limnodynastidae,Neobatrachus,,"Peters, 1863",Https://biodiversity.org.au/afd/taxa/43ca4aa9-...
3,Animalia,Chordata,Amphibia,Anura,Limnodynastidae,Adelotus,,"Ogilby, 1907",Https://biodiversity.org.au/afd/taxa/704945f7-...
4,Animalia,Chordata,Amphibia,Anura,Limnodynastidae,Heleioporus,,"Gray, 1841",Https://biodiversity.org.au/afd/taxa/990ee116-...
5,Animalia,Chordata,Amphibia,Anura,Limnodynastidae,Notaden,,"Günther, 1873",Https://biodiversity.org.au/afd/taxa/5ca85ae2-...
6,Animalia,Chordata,Amphibia,Anura,Limnodynastidae,Philoria,,"Spencer, 1901",Https://biodiversity.org.au/afd/taxa/494f8b10-...
7,Animalia,Chordata,Amphibia,Anura,Limnodynastidae,Lechriodus,,"Boulenger, 1882",Https://biodiversity.org.au/afd/taxa/e8b35b47-...

### Austrian atlas

In [7]:
galah.galah_config(atlas="Austria")

In [8]:
galah.atlas_species(taxa="Sehirus")

,kingdom,phylum,class,order,family,genus,species,vernacular_name,author,guid
0,Animalia,Arthropoda,Insecta,Hemiptera,Cydnidae,Sehirus,Sehirus luctuosus,,"Mulsant & rey, 1866",4486163
1,Animalia,Arthropoda,Insecta,Hemiptera,Cydnidae,Sehirus,Sehirus tibialis,,,8810970
2,Animalia,Arthropoda,Insecta,Hemiptera,Cydnidae,Sehirus,Sehirus morio,,"(linnaeus, 1761)",2078781

In [9]:
galah.atlas_species(taxa="Sehirus",rank="subspecies")

ValueError: subspecies is not a valid rank for the Austria atlas.  Possible ranks are:

kingdom, phylum, class, order, family, genus, species

In [10]:
galah.atlas_species(taxa="Cydnidae")

,kingdom,phylum,class,order,family,genus,species,vernacular_name,author,guid
0,Animalia,Arthropoda,Insecta,Hemiptera,Cydnidae,Tritomegas,Tritomegas bicolor,Schwarzweiße Erdwanze,"(linnaeus, 1758)",5758805
1,Animalia,Arthropoda,Insecta,Hemiptera,Cydnidae,Tritomegas,Tritomegas sexmaculatus,,"(rambur, 1839)",5758809
2,Animalia,Arthropoda,Insecta,Hemiptera,Cydnidae,Tritomegas,,,"Amyot & serville, 1843",3265258
3,Animalia,Arthropoda,Insecta,Hemiptera,Cydnidae,Canthophorus,Canthophorus impressus,,"(horváth, 1881)",4486152
4,Animalia,Arthropoda,Insecta,Hemiptera,Cydnidae,Canthophorus,,,"Mulsant & rey, 1866",4289992
5,Animalia,Arthropoda,Insecta,Hemiptera,Cydnidae,Adomerus,Adomerus biguttatus,,"(linnaeus, 1758)",4486134
6,Animalia,Arthropoda,Insecta,Hemiptera,Cydnidae,Adomerus,,,"Mulsant & rey, 1866",4405030
7,Animalia,Arthropoda,Insecta,Hemiptera,Cydnidae,Legnotus,Legnotus limbosus,,"(geoffroy, 1785)",5758810
8,Animalia,Arthropoda,Insecta,Hemiptera,Cydnidae,Legnotus,Legnotus picipes,,"(fallén, 1807)",5758812
9,Animalia,Arthropoda,Insecta,Hemiptera,Cydnidae,Legnotus,,,"Schiødte, 1848",3265255
10,Animalia,Arthropoda,Insecta,Hemiptera,Cydnidae,Canthophorus,Canthophorus dubius,,"(scopoli, 1763)",4486159
11,Animalia,Arthropoda,Insecta,Hemiptera,Cydnidae,Cydnus,Cydnus aterrimus,Gemeine Erdwanze,"(forster, 1771)",2078815
12,Animalia,Arthropoda,Insecta,Hemiptera,Cydnidae,Cydnus,Cydnus capicola,,,8905192
13,Animalia,Arthropoda,Insecta,Hemiptera,Cydnidae,Sehirus,Sehirus luctuosus,,"Mulsant & rey, 1866",4486163
14,Animalia,Arthropoda,Insecta,Hemiptera,Cydnidae,Sehirus,Sehirus tibialis,,,8810970
15,Animalia,Arthropoda,Insecta,Hemiptera,Cydnidae,Microporus,Microporus nigrita,Schwarze Sand-Erdwanze,"(j.c.fabricius, 1794)",5758803
16,Animalia,Arthropoda,Insecta,Hemiptera,Cydnidae,Canthophorus,Canthophorus melanopterus,,"(herrich-schäffer, 1835)",4486146
17,Animalia,Arthropoda,Insecta,Hemiptera,Cydnidae,Canthophorus,Canthophorus melanopterus,,"(wagner, 1956)",4486147
18,Animalia,Arthropoda,Insecta,Hemiptera,Cydnidae,Sehirus,Sehirus morio,,"(linnaeus, 1761)",2078781
19,Animalia,Arthropoda,Insecta,Hemiptera,Cydnidae,Legnotus,Legnotus fumigatus,,"(a.costa, 1853)",7675916
20,Animalia,Arthropoda,Insecta,Hemiptera,Cydnidae,Legnotus,,,"Schiødte, 1848",3265255
21,Animalia,Arthropoda,Insecta,Hemiptera,Cydnidae,Ochetostethus,Ochetostethus nanus,,"(herrich-schaeffer, 1834)",4486192
22,Animalia,Arthropoda,Insecta,Hemiptera,Cydnidae,Tritomegas,Tritomegas rotundipennis,,"(dohrn, 1862)",7961766
23,Animalia,Arthropoda,Insecta,Hemiptera,Cydnidae,Tritomegas,,,"Amyot & serville, 1843",3265258

In [11]:
galah.atlas_species(taxa="Cydnidae",rank="genus")

,kingdom,phylum,class,order,family,genus,vernacular_name,author,guid
0,Animalia,Arthropoda,Insecta,Hemiptera,Cydnidae,Tritomegas,,"Amyot & serville, 1843",3265258
1,Animalia,Arthropoda,Insecta,Hemiptera,Cydnidae,Tritomegas,,"(lindberg, 1932)",9134791
2,Animalia,Arthropoda,Insecta,Hemiptera,Cydnidae,Canthophorus,,"Mulsant & rey, 1866",4289992
3,Animalia,Arthropoda,Insecta,Hemiptera,Cydnidae,Canthophorus,,"Asanova, 1964",4486154
4,Animalia,Arthropoda,Insecta,Hemiptera,Cydnidae,Canthophorus,,"(horváth, 1899)",4486155
5,Animalia,Arthropoda,Insecta,Hemiptera,Cydnidae,Canthophorus,,"Asanova, 1964",10709547
6,Animalia,Arthropoda,Insecta,Hemiptera,Cydnidae,Legnotus,,"Schiødte, 1848",3265255
7,Animalia,Arthropoda,Insecta,Hemiptera,Cydnidae,Adomerus,,"Mulsant & rey, 1866",4405030
8,Animalia,Arthropoda,Insecta,Hemiptera,Cydnidae,Adomerus,,"Jakovlev, 1879",10885170
9,Animalia,Arthropoda,Insecta,Hemiptera,Cydnidae,Adomerus,,"(linnaeus, 1758)",4486134
10,Animalia,Arthropoda,Insecta,Hemiptera,Cydnidae,Sehirus,,"Amyot & serville, 1843",2078780
11,Animalia,Arthropoda,Insecta,Hemiptera,Cydnidae,Sehirus,,,8810970
12,Animalia,Arthropoda,Insecta,Hemiptera,Cydnidae,Sehirus,,,7199457
13,Animalia,Arthropoda,Insecta,Hemiptera,Cydnidae,Sehirus,,"Horvath, 1895",10888587
14,Animalia,Arthropoda,Insecta,Hemiptera,Cydnidae,Cydnus,,"Fabricius, 1803",2078814
15,Animalia,Arthropoda,Insecta,Hemiptera,Cydnidae,Cydnus,,,8905192
16,Animalia,Arthropoda,Insecta,Hemiptera,Cydnidae,Cydnus,,"Theobald, 1937",8689824
17,Animalia,Arthropoda,Insecta,Hemiptera,Cydnidae,Microporus,,"Uhler, 1872",2078797
18,Animalia,Arthropoda,Insecta,Hemiptera,Cydnidae,Ochetostethus,,"Fieber, 1860",4404611
19,Animalia,Arthropoda,Insecta,Hemiptera,Cydnidae,Ochetostethus,,"Wagner, 1952",10754491
20,Animalia,Arthropoda,Insecta,Hemiptera,Cydnidae,Ochetostethus,,"Magnien, 2006",4486189
21,Animalia,Arthropoda,Insecta,Hemiptera,Cydnidae,Ochetostethus,,"Wagner, 1940",4486194

### Brazilian atlas

In [12]:
galah.galah_config(atlas="Brazil")

In [13]:
galah.atlas_species(taxa="Ramphastos")

,kingdom,phylum,class,order,family,genus,species,vernacular_name,author,guid
0,Animalia,Chordata,Aves,Piciformes,Ramphastidae,Ramphastos,Ramphastos toco,"Japu, Tucanuçu",Pallas,
1,Animalia,Chordata,Aves,Piciformes,Ramphastidae,Ramphastos,Ramphastos vitellinus,,Fraga,
2,Animalia,Chordata,Aves,Piciformes,Ramphastidae,Ramphastos,Ramphastos dicolorus,Japu-Verde,"Linnaeus, 1766",
3,Animalia,Chordata,Aves,Piciformes,Ramphastidae,Ramphastos,Ramphastos tucanus,,,

In [14]:
galah.atlas_species(taxa="Ramphastos",rank="subspecies")

,kingdom,phylum,class,order,family,genus,species,subspecies,vernacular_name,author,guid
0,Animalia,Chordata,Aves,Piciformes,Ramphastidae,Ramphastos,Ramphastos vitellinus,Ramphastos vitellinus ariel,Iraúna-De-Bico-Branco,"Vigors, 1826",
1,Animalia,Chordata,Aves,Piciformes,Ramphastidae,Ramphastos,Ramphastos tucanus,Ramphastos tucanus cuvieri,,"Wagler, 1827",
2,Animalia,Chordata,Aves,Piciformes,Ramphastidae,Ramphastos,Ramphastos vitellinus,Ramphastos vitellinus vitellinus,Japuíra,"Lichtenstein, 1823",
3,Animalia,Chordata,Aves,Piciformes,Ramphastidae,Ramphastos,Ramphastos toco,Ramphastos toco albogularis,,"Cabanis, 1862",
4,Animalia,Chordata,Aves,Piciformes,Ramphastidae,Ramphastos,Ramphastos tucanus,Ramphastos tucanus tucanus,,"Linnaeus, 1758",
5,Animalia,Chordata,Aves,Piciformes,Ramphastidae,Ramphastos,Ramphastos vitellinus,Ramphastos vitellinus culminatus,,"Gould, 1833",
6,Animalia,Chordata,Aves,Piciformes,Ramphastidae,Ramphastos,Ramphastos toco,Ramphastos toco toco,Japuguaçu,"Statius muller, 1776",